using FluentValidation;
using FluentValidation.Validators;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace Api.Validation;

/// <summary>
/// OpenAPI schema transformer that reflects FluentValidation rules into the generated
/// schema so the spec advertises the same constraints the runtime enforces.
/// <para>
/// Currently mirrored constraints: <c>required</c> (from <see cref="INotEmptyValidator"/>
/// or <see cref="INotNullValidator"/>), <c>maxLength</c> / <c>minLength</c> (from
/// <see cref="ILengthValidator"/>), and <c>pattern</c> (from <see cref="IRegularExpressionValidator"/>).
/// Add more here as we adopt them — see the test in <c>OpenApiSpecTests</c> for the
/// regression guard.
/// </para>
/// <para>
/// Property-name mapping goes through <see cref="JsonPropertyNaming.ToJsonName"/> — the
/// same helper <c>ValidationEndpointFilter</c> uses for runtime error keys, so the schema
/// and the validation error envelope describe the same field names.
/// </para>
/// </summary>
internal sealed class FluentValidationSchemaTransformer : IOpenApiSchemaTransformer
{
    public Task TransformAsync(
        OpenApiSchema schema,
        OpenApiSchemaTransformerContext context,
        CancellationToken cancellationToken)
    {
        var clrType = context.JsonTypeInfo.Type;
        var validatorType = typeof(IValidator<>).MakeGenericType(clrType);
        if (context.ApplicationServices.GetService(validatorType) is not IValidator validator)
        {
            return Task.CompletedTask;
        }

        var descriptor = validator.CreateDescriptor();

        foreach (var member in descriptor.GetMembersWithValidators())
        {
            var clrName = member.Key;
            var jsonName = JsonPropertyNaming.ToJsonName(clrName);

            if (schema.Properties is null || !schema.Properties.TryGetValue(jsonName, out var propSchemaReadOnly))
            {
                continue;
            }

            // schema.Properties exposes IOpenApiSchema (read-only). Cast to the mutable
            // concrete type so we can stamp constraints onto it. Inline property schemas
            // generated by ASP.NET are always OpenApiSchema instances.
            if (propSchemaReadOnly is not OpenApiSchema propSchema)
            {
                continue;
            }

            foreach (var rule in member)
            {
                switch (rule.Validator)
                {
                    case INotEmptyValidator:
                    case INotNullValidator:
                        schema.Required ??= new HashSet<string>();
                        schema.Required.Add(jsonName);
                        break;

                    case ILengthValidator length:
                        if (length.Max > 0)
                        {
                            propSchema.MaxLength = length.Max;
                        }
                        if (length.Min > 0)
                        {
                            propSchema.MinLength = length.Min;
                        }
                        break;

                    case IRegularExpressionValidator regex:
                        propSchema.Pattern = regex.Expression;
                        break;
                }
            }
        }

        return Task.CompletedTask;
    }
}
