namespace MyStack.Auth.Data;

public enum PermissionOverrideKind
{
    Grant,
    Deny,
}

// Architecture §3.1's override row: a permission the user's roles don't decide — granted on top of
// them or denied despite them. The string is opaque here; the API owns the catalog and does the
// arithmetic. §3.2's impersonation access grant is designed as a sibling of this shape (subject,
// expiry, audit trail), so changes to it should keep that door open.
public sealed class PermissionOverride
{
    public PermissionOverride()
    {
        // Same key strategy as ApplicationUser: version 7, generated by the application.
        Id = Guid.CreateVersion7();
    }

    public Guid Id { get; init; }

    public required Guid UserId { get; init; }

    public required string Permission { get; init; }

    public required PermissionOverrideKind Kind { get; init; }

    /// <summary>Past this instant the row stops minting its claim. Null never expires.</summary>
    public DateTimeOffset? ExpiresAt { get; init; }

    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
}
