<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MyStack.Jobs.Tests" />
  </ItemGroup>
</Project>
